### ISSUE TITLE
Security Test Scanning/Report

### ISSUE THREAD

**Issue by jredingcvs** [CognizantOpenSource/maqs-java#35]
**Add**
- [ ] Security Scanning/Reporting - Selenium Proxy Setup #34 Selenium Proxy Setup
- [ ] Security Scanning/Reporting - Web Service Proxy Set Up #33 Web Service Proxy Setup
- [ ] Report Generation and Storage

**Review**
- []

**Remove**
- []

**Branches/PRs**

**Notes**
